### ISSUE TITLE
Tab bar pushes too close to the edges of the screen on small devices

### ISSUE THREAD

**Issue by jesster2k10** [gorhom/react-native-animated-tabbar#10]
# Bug

As described in the title and shown in the screenshot below. It happens when there is more than 4 tab bar items and you are using a small device (this is taken from an iPhone 8)

![Screenshot 2020-04-10 at 12 41 32](https://user-images.githubusercontent.com/6454286/78988353-9cee6980-7b28-11ea-8a4a-41bc1c8a4aeb.png)

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/animated-tabbar         | https://github.com/jesster2k10/react-native-animated-tabbar.git   |
| react-native                    | 0.61.5   |
| react-native-reanimated         | ^1.7.0  |
| react-native-gesture-handler    | ^1.5.3   |
| react-native-svg                | ^12.0.3  |

## Steps To Reproduce

Setup a tab bar with more than 4 screens and run it on an iPhone 8 or smaller.

Describe what you expected to happen:

There should be adequate spacing between the edges of the screen and the tab bar on smaller devices.

A possible solution would be to decrease the spacing between items on smaller devices or the font sizes/width to provide a better UI.

**Comment by gorhom** [comment]
hi @jesster2k10 , thanks for reporting the bug and creating a PR.

I will review it now :))

**Comment by jesster2k10** [comment]
Okay, I can confirm that the PR did indeed work. Here is a side by side of the default (12) spacing on an iPhone 8 and the reduced (8) spacing

It's worth nothing that setting a spacing to 0 or negative spacing seems to have no effect.

![Simulator Screen Shot - iPhone 8 - 2020-04-13 at 21 40 12](https://user-images.githubusercontent.com/6454286/79159086-5ec6a380-7dcf-11ea-9b78-49902fbc3659.png)

![Simulator Screen Shot - iPhone 8 - 2020-04-13 at 21 39 57](https://user-images.githubusercontent.com/6454286/79159076-566e6880-7dcf-11ea-9d17-f9095307bad1.png)

**Comment by jesster2k10** [comment]
I'll run it on different sized devices now to confirm

**Comment by jesster2k10** [comment]
I can confirm it works great on smaller/larger devices too with the following setup based on this gist here https://gist.github.com/jesster2k10/6a25236328f9ff6992da29d7c24a76b7

```tsx
const tabBarOptions = {
  itemOuterSpace: {
    horizontal: selectDevice({
      xsmall: 0,
      small: 2,
      normal: 8,
      default: 12,
    }),
    vertical: ifIphoneX(8, 8),
  },
}
```

A screenshot taken from an iPhone SE

![Simulator Screen Shot - iPhone SE - 2020-04-13 at 22 03 07](https://user-images.githubusercontent.com/6454286/79160962-984cde00-7dd2-11ea-8766-143e195f5c9b.png)
