### ISSUE TITLE
Uncaught TypeError: Object(...) is not a function

### ISSUE THREAD

**Issue by r0hin** [gorhom/react-native-animated-tabbar#100]
# Bug

TypeError: Object(...) is not a function error will occur on compile. Error looks like this:
```
Uncaught TypeError: Object(...) is not a function
    at Module.../../../../../../../../../../Desktop/Code/personal-project/echomobile2/node_modules/@react-native-community/masked-view/js/MaskedView.js (MaskedView.js:14)
    at __webpack_require__ (bootstrap:789)
    at fn (bootstrap:100)
    at Module.../../../../../../../../../../Desktop/Code/personal-project/echomobile2/node_modules/@react-native-community/masked-view/index.js (index.js:1)
    at __webpack_require__ (bootstrap:789)
    at fn (bootstrap:100)
    at 
...
```

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/animated-tabbar         | ^2.1.1   |
| react-native                    | 40.0.1   |
| react-native-reanimated         | ~1.13.0   |
| react-native-gesture-handler    | ^1.9.0   |
| react-native-svg                | 12.1.0   |

## Steps To Reproduce

1. Use the sample code
2. On compile there is an error on me

Describe what you expected to happen:
No error

## Reproducible sample code
https://pastebin.com/raw/pqcfVrw4

Thanks for your help (I might just be doing something wrong!)

**Comment by gorhom** [comment]
you need to set icon components like this
```tsx
component: props => <Feather {...props} name="activity" size={24} color="black" />,
```

**Comment by r0hin** [comment]
I've set it. However, same error.
Full code: https://pastebin.com/raw/MYY5enG0
Thanks for your help! @gorhom

**Comment by r0hin** [comment]
> you need to set icon components like this
> 
> ```tsx
> component: props => <Feather {...props} name="activity" size={24} color="black" />,
> ```

@gorhom, I have made the change to no avail. Consider reopening. Thanks.
