### ISSUE TITLE
Tap action not working in android

### ISSUE THREAD

**Issue by kuldip-techholding** [gorhom/react-native-animated-tabbar#103]
<img width="316" alt="Screenshot 2021-02-16 at 10 47 14 PM" src="https://user-images.githubusercontent.com/63836311/108098051-eb558880-70a8-11eb-9cd6-d0b062596293.png">

**Comment by k2an** [comment]
Same Problem i have got also. There is no console error. Waiting for a good solution.

**Comment by neiracausevic1** [comment]
Same, is there a workaround?

**Comment by emirajaawn** [comment]
I have the same problem, did exactly like the example, but then tap does not work

```
"@gorhom/animated-tabbar": "^2.1.1",
    "@react-native-community/masked-view": "^0.1.10",
    "@react-navigation/bottom-tabs": "^5.11.8",
    "@react-navigation/native": "^5.9.3",
    "@react-navigation/stack": "^5.14.3",
    "metro-config": "^0.65.2",
    "react": "17.0.1",
    "react-native": "0.64.0",
    "react-native-feather": "^1.0.2",
    "react-native-gesture-handler": "^1.10.3",
    "react-native-paper": "^4.7.2",
    "react-native-reanimated": "^2.0.0",
    "react-native-safe-area-context": "^3.2.0",
    "react-native-screens": "^2.18.1",
    "react-native-svg": "^12.1.0",
    "react-native-svg-transformer": "^0.14.3",
    "react-navigation": "^4.4.4"
```

@gorhom

**Comment by darkbasic** [comment]
Did someone manage to find a workaround?

**Comment by darkbasic** [comment]
It's not a bug in the library, but a misconfiguration in react-native-gesture-handler: https://docs.swmansion.com/react-native-gesture-handler/docs/#updating-mainactivityjava

This should be closed.

**Comment by briantanabe** [comment]
Again @darkbasic what is that link referring to? This bug currently affects me as well, and there's no explanation as how to fix it, even if it's independent of this library.
