### ISSUE TITLE
Is this lib maintained anymore?

### ISSUE THREAD

**Issue by chris-hinds** [gorhom/react-native-animated-tabbar#117]
I'm seeing lots of issues that go unanswered and there are a host of different issues with the last few version of this library (most seem to be with the version of reanimated or redash used).

I'd love to continue using this library but right now its causing my app to error constantly.

**Comment by gorhom** [comment]
currently im busy with [Bottom Sheet](https://github.com/gorhom/react-native-bottom-sheet) new release, once i done with it, i will prepare this library for a new major release 

- Rewrite in Reanimated v2
- Support React Navigation v6
- Allow users to write their own custom tab bars

**Comment by chris-hinds** [comment]
Thats great news, thanks for the reply @gorhom Please us know if the community can help in anyway. Id be happy to help test out any betas

**Comment by gorhom** [comment]
@chris-hinds feel free to add your feedback here https://github.com/gorhom/react-native-animated-tabbar/discussions/118
