### ISSUE TITLE
Icon animation

### ISSUE THREAD

**Issue by Angelk90** [gorhom/react-native-animated-tabbar#15]
# Feature Request

![](https://mir-s3-cdn-cf.behance.net/project_modules/max_1200/c169bb79473185.5cc3fd6d943ad.gif)

## Why it is needed
In order to give a little dynamism to everything.

**Comment by nghiatv** [comment]
Try it in [Lottie react native ](https://github.com/react-native-community/lottie-react-native) and conditional render tabbar when focused or not. It's no need react native animated

**Comment by gorhom** [comment]
@nghiatv yeah that's correct, but i think i'll need to provide `animatedFocus` AnimatedNode to icon component, to let user customise their icon animation 💡

thanks @Angelk90  for reporting this :)

**Comment by Angelk90** [comment]
@gorhom : So do you think you will implement this feature?

**Comment by gorhom** [comment]
@Angelk90 , i will only provide `animatedFocus` with icon props, then you could use it to animate your icons.

**Comment by Angelk90** [comment]
@gorhom : You could post an example online on https://snack.expo.io, also with an example of an animated tabBar for example: https://snack.expo.io/Dw_Njk940

**Comment by nandorojo** [comment]
As mentioned in #19, I think it would be useful to also provide a boolean here, the way react navigation does, in addition to a color string that is not an animated value. Not all icon libraries support animated values.

**Comment by muxbert** [comment]
when the  ```animatedFocus``` is going to be shipped?

**Comment by gorhom** [comment]
@muxbert this weekend :)

**Comment by gorhom** [comment]
`animatedFocus` been add with the new release 👍
https://github.com/gorhom/react-native-animated-tabbar/releases/tag/v1.1.0

**Comment by muxbert** [comment]
How am I suppose to use this ?

I tried this way :

 ```Home: {
    labelStyle: {
      color: '#FF5A19',
    },
    icon: {
      component: ({color, size, animatedFocus}) =>
        animatedFocus ? (
          <AnimatedMaterialIcons size={size} color={color} name={'home'} />
        ) : (
          <AnimatedMaterialIcons
            size={size}
            color={color}
            name={'home-outline'}
          />
        ),
      activeColor: '#FF5A19',
      inactiveColor: '#969696',
    },```

And this way also:

```
Home: {
    labelStyle: {
      color: '#FF5A19',
    },
    icon: {
      component: ({color, size, animatedFocus}) =>

          <AnimatedMaterialIcons size={size} color={color} name={ animatedFocus ? 'home' : 'home-outline' } />

      activeColor: '#FF5A19',
      inactiveColor: '#969696',
    },
```

None of them worked.

**Comment by Angelk90** [comment]
@gorhom :
I'm trying the example file, but I don't understand how to create an animated tabbar example as in the figure.

You could publish an example, in case also with the use of lottie.

**Comment by gorhom** [comment]
@Angelk90 you will need to use `useCode` to play/stop lottie based on `animatedFocus`
