### ISSUE TITLE
Badge

### ISSUE THREAD

**Issue by Angelk90** [gorhom/react-native-animated-tabbar#16]
# Feature Request

![](https://i.ytimg.com/vi/ajVVjuOSlV4/maxresdefault.jpg)

## Why it is needed

Being able to indicate via a badge in the icon would allow you to suggest on any page that there are new updates.

**Comment by gorhom** [comment]
@Angelk90 you could achieve this by following React Navigation docs: [Add badge to icons](https://reactnavigation.org/docs/tab-based-navigation#add-badges-to-icons) 👍

**Comment by gorhom** [comment]
![image](https://user-images.githubusercontent.com/4061838/90068175-83d11180-dcf0-11ea-9d97-b8f68ae6a2f7.png)

i have added icon with badge in the styled examples 👍
