### ISSUE TITLE
Add focused boolean prop to icon

### ISSUE THREAD

**Issue by nandorojo** [gorhom/react-native-animated-tabbar#19]
https://github.com/gorhom/react-native-animated-tabbar/blob/d4793271ca1b2558dc35bf5e0e34b7e8c79758a2/src/bubble/item/BubbleTabBarItem.tsx#L189

**`src/bubble/item/BubbleTabBarItem.tsx`**

Add a `focused` boolean to the custom Icon render function:
```typescript
  // render
  const renderIcon = () => {
    return typeof icon.component === 'function'
      ? icon.component({ color: animatedIconColor, size: iconSize, focused: index === selectedIndex })
      : icon.component;
  };
```

Also, add this in the typescript definition:

https://github.com/gorhom/react-native-animated-tabbar/blob/d4793271ca1b2558dc35bf5e0e34b7e8c79758a2/src/types.ts#L9

**`src/types.ts`**
```typescript
export interface TabConfigsType {
  labelStyle: TextStyle;
  icon: {
    component:
      | ((props: {
          color: Animated.Node<string | number>;
          size: number;
          focused: boolean // 👋 addition
        }) => React.ReactNode)
      | React.ReactNode;
    activeColor: string;
    inactiveColor: string;
  };
  background: {
    activeColor: string;
    inactiveColor: string;
  };
}
```

**Comment by gorhom** [comment]
yeah , i was planning for this, but instead of a `boolean`, it will be an animated value  https://github.com/gorhom/react-native-animated-tabbar/issues/15#issuecomment-616371189

**Comment by nandorojo** [comment]
Would it be possible to use both? I’m using an icon library that doesn’t work with animated values. (@expo/vector-icons)

**Comment by nandorojo** [comment]
Ah, this works too:

```typescript
import Ionicons from '@expo/vector-icons/Ionicons'
import Animated from 'react-native-reanimated'

const Icon = Animated.createAnimatedComponent(Ionicons)

const tabs: TabsConfigsType<MainTabsParams> = {
  dashboard: {
    labelStyle: {
      color: ThemeUi.colors.text,
    },
    icon: {
      component: ({ color, size }) => (
        <Icon size={size} color={color} name="ios-musical-note" />
      ),
      activeColor: `${ThemeUi.colors.text}`,
      inactiveColor: 'rgba(0,0,0,1)',
    },
    background: {
      activeColor: `${ThemeUi.colors.primary}`,
      inactiveColor: 'rgba(223,215,243,0)',
    },
  },
}
```

**Comment by Angelk90** [comment]
@nandorojo : Could you post a complete example on https://snack.expo.io/?

**Comment by hugoh59** [comment]
I get the following error when I add the color prop to my icon component, using FeatherIcon libary the same way as you.

> TypeError: Cannot add property 13, object is not extensible
