### ISSUE TITLE
Add description for `Animated.addWhitelistedNativeProps`

### ISSUE THREAD

**Issue by danielwinkler** [gorhom/react-native-animated-tabbar#21]
# Feature Request

It would be nice to explicitly add some information for 
`Animated.addWhitelistedNativeProps`

## Why it is needed

Otherwise reanimated will constantly emit notifications over the bridge.
I see it in your SVG examples, but missed out initially.

I want to use this ticket also to thank you for this awesome package!

**Comment by gorhom** [comment]
Hi @danielwinkler , good catch right there 👍

actually it was something that @owinter86 suggested, you can read his investigation here (https://github.com/software-mansion/react-native-reanimated/issues/537),

i will add small description of it on the next release, thanks

**Comment by gorhom** [comment]
note added in https://github.com/gorhom/react-native-animated-tabbar/commit/082f3b5a2315cce8be66077e94e9a798ffd35b05 👍

**Comment by danielwinkler** [comment]
Great thanks!

i hadn’t seen that you whitelist it by default.
my example animated the fill property so your defaults didn’t cover it.

that’s why i thought it would be nice to add it to the README. as the SVGs in the example whitelist it explicitly.

maybe you could even allow to pass the animated properties as arg to tabbar, so that you can whitelist the correct ones.
