### ISSUE TITLE
Example on https://snack.expo.io/

### ISSUE THREAD

**Issue by Angelk90** [gorhom/react-native-animated-tabbar#22]
# Feature Request

## Why it is needed

Hi @gorhom , it would be very useful to have working examples on https://snack.expo.io/

**Comment by gorhom** [comment]
hi @Angelk90, sorry but i do not use Expo, but i think you could copy the examples code base and run it on expo smoothly.

[examples source code](https://github.com/gorhom/react-native-animated-tabbar/tree/master/example/src/screens)

**Comment by Angelk90** [comment]
@gorhom , 
I tried to recreate your example on Expo, but it doesn't seem to work, here is the link: https://snack.expo.io/NpIwPZ!uo

There seems to be some problem with `react-navigation`.
