### ISSUE TITLE
Long press activates an effect

### ISSUE THREAD

**Issue by Angelk90** [gorhom/react-native-animated-tabbar#25]
# Feature Request

Linkedin:
![](https://i.imgur.com/SC6EdBS.jpg)

Hi @gorhom ,

by clicking on an element of the tabbar, normal behavior should change screen.

But a long press on an element of the tabbar could trigger an effect.

For example, as seen in the image it makes a tooltip or popper appear.

Instagram, for example, to a different behavior, if you click on the last element of the tabbar, it allows you to switch accounts.

## Why it is needed

To give a little originality to everything.

**Comment by gorhom** [comment]
yeah that something has to be added 👍
