### ISSUE TITLE
Flash Preset behaves strangely at React Native 0.61.5

### ISSUE THREAD

**Issue by harucsx** [gorhom/react-native-animated-tabbar#30]
# Bug
Hello, This library is awesome!
but, Flash Preset behaves strangely at React Native 0.61.5.

The example provided works very well, 
but if you change the react native version to 0.61.5, the bug is reproduced.

It only happens on Android.

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/animated-tabbar         | 1.2.0   |
| react-native                    | 0.61.5   |
| react-native-reanimated         | 1.7.0   |
| react-native-gesture-handler    | 1.6.0   |
| react-native-svg                | 12.1.0   |

## Steps To Reproduce

1. Use animated-tabbar on react native 0.61.5 

![screenshot_1](https://user-images.githubusercontent.com/6668916/80907916-d005d080-8d55-11ea-9101-eeec9a2b15f2.gif)

Thank you.

**Comment by harucsx** [comment]
It only happens on Android.

**Comment by gorhom** [comment]
hi @harucsx , thanks for reporting this issue , i'll investigate it as soon as i get free time :)
