### ISSUE TITLE
Expensive iOS CPU usage 

### ISSUE THREAD

**Issue by muxbert** [gorhom/react-native-animated-tabbar#31]
# Bug

While running on iOS simulator there was a huge noticeable CPU usage when using this nice library which causes drop in the whole app performance.

![ezgif-7-f7729bbbc3eb](https://user-images.githubusercontent.com/60647004/81287859-2cc1fd80-906c-11ea-8fe6-1f9d54561e08.gif)

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/animated-tabbar         | 1.2.0   |
| react-native                    | 0.61   |
| react-native-reanimated         | 1.8.0   |
| react-native-gesture-handler    | 1.6.1   |
| react-native-svg                | 12.1.0   |

## Reproducible sample code

By just simply adding it as a prop: 
tabBar={props => (
      <AnimatedTabBar
        isRTL={I18nManager.isRTL}
        duration={500}
        iconSize={29}
        //itemOuterSpace={{horizontal:20}}
        itemInnerSpace={{horizontal: 15,}}
        style={{
          shadowOffset: {
            height: 0,
            width: 0,
          },
          shadowColor: 'rgba(0,0,0,0.16)',
          shadowRadius: 5,
          shadowOpacity: 0.4,
          backgroundColor: '#FFFFFF',
          height: hasNotch ? 98 : null,
          paddingHorizontal: 0,
          elevation: 12,
        }}
        tabs={tabs}
        {...props}
      />
    )}

**Comment by gorhom** [comment]
@muxbert , thanks for reporting this i'll prioritise solving this issue 👍
