### ISSUE TITLE
Endless loop when multiple taps on buttons

### ISSUE THREAD

**Issue by outaTiME** [gorhom/react-native-animated-tabbar#36]
Hi guys, if we multi tap too fast on buttons i get neverending loop, 

here the video:

![RPReplay_Final1589747950](https://user-images.githubusercontent.com/140472/82159633-f8b5bc00-9865-11ea-9557-d28e750d2d8d.gif)

**Comment by gorhom** [comment]
hi @outaTiME , thanks for reporting the issue, but in order to help you please edit this issue and follow the bug report template.
