### ISSUE TITLE
Error observed

### ISSUE THREAD

**Issue by GodwinEbikwo** [gorhom/react-native-animated-tabbar#4]
undefined is not a function (near '...(0, _reactNativeReanimated.useCode)...')

**Comment by jackgisel** [comment]
Having the same issue. Using expo, and implemented it into a Javascript project.

**Comment by jackgisel** [comment]
![image](https://user-images.githubusercontent.com/22860569/78065329-fb0c9700-7347-11ea-8eb3-5bc4e3407536.png)
Here is the image for reference. I am available for help and maintaining if needed :)

**Comment by gorhom** [comment]
hi @GodwinEbikwo , @jackgisel 
thanks for reporting the issue , i didn't test the library on Expo projects but i can assume that the Reanimated version is old. however PRs are always welcome 🙌

**Comment by gorhom** [comment]
Hi @GodwinEbikwo , @jackgisel ,

plea
