### ISSUE TITLE
How to translate the tabs?

### ISSUE THREAD

**Issue by efstathiosntonas** [gorhom/react-native-animated-tabbar#44]
Hey @gorhom, i'm the guy from reddit with the translation issues. 

Here's a repo to reproduce: 
https://github.com/efstathiosntonas/react-native-animated-tabbar-translated

When you first open the app it will display an error `Cannot read property of 'inactiveColor' of undefined`. That's because js reads the code inside the `tabs` array before i18n is initialized. Can you think of a solution?

I've tried converting `tabs` into a function and pass `translate` to it, that way it works but changing tabs no longer works, it stays on the same screen even though tabs are being highlighted (because of useMemo/memo maybe?)

eg: 

```<AnimatedTabBar tabs={tabs(translate} {...props} />```

**Comment by gorhom** [comment]
hi @efstathiosntonas , thanks for reporting this issue, but actually this is not an issue with this library, but with the implementation of i18n.

i have a working fix locally , i could push it your repo but i'll need you to give me access to the repo first :)

**Comment by efstathiosntonas** [comment]
Gey @gorhom thanks for looking into thus. I’ve added you as a collaborator on the repo 👍

**Comment by Angelk90** [comment]
@efstathiosntonas : Why closed, did you find the solution?

**Comment by efstathiosntonas** [comment]
@Angelk90 the repo on the first message is working fine, please take a look.

**Comment by Angelk90** [comment]
@efstathiosntonas : 

If I understand correctly the solution would be to use this:

```javascript
options={{ tabBarLabel: translate('NAME') }}
```
