### ISSUE TITLE
Bottom Bar Complete Style Change Customization

### ISSUE THREAD

**Issue by WrathChaos** [gorhom/react-native-animated-tabbar#46]
# Feature Request

I would like to change the whole bottom bar's style change. If this would be optional, it will be great. Actually I just want to change some border radius and the colors and maybe add a shadow. Is that possible to let us change the style? 
(I tried to add border radius via 'style' prop but bottom side there is a white background all the time) 
Maybe it is because of the Navigation part but I could not fix it. Maybe you can guide me

## Why it is needed

More customization possibilities.

### Code sample

        <AnimatedTabBar preset="flashy" tabs={tabs} iconSize={25} style={{borderRadius:16, backgroundColor:"#059505,  ...shadowStyles}} {...props} />

**Comment by gorhom** [comment]
hi @WrathChaos, i will look in to it this weekend :)

**Comment by gorhom** [comment]
hi @WrathChaos , i have looked at this issue and it is doable, but here are things to take in consideration:

`React Navigation` is setting the bottom tab bar position as a `relative` to insure that it will push the content height based on its height, so if we set it to `absolute` where we will have our tab bar float, the height of the screen content will take over the whole device screen height, so you will need to handle setting your custom tab bar height as bottom padding on every screen :( 

However, i notice that i hard setting `safeAreaInsets`, which i will update this to inherent it from `React Navigation` to allow you to control it

![image](https://user-images.githubusercontent.com/4061838/83979758-01ebf300-a911-11ea-9195-a9dfe6a29b53.png)

^ this is a screen without the bottom bar height added as bottom padding

**Comment by gorhom** [comment]
<img width="806" alt="Screenshot 2020-06-07 at 23 30 49" src="https://user-images.githubusercontent.com/4061838/83980695-08319d80-a918-11ea-9061-ef3605618120.png">

^ i got this working , tomorrow i'll prepare a new release :)

**Comment by WrathChaos** [comment]
You're awesome man :D Thank you so much, waiting for the new release. Also, this looks great :D Please share this as an example.

**Comment by gorhom** [comment]
@WrathChaos this been released with v1.5.1 🎉

**Comment by WrathChaos** [comment]
Thank you so much @gorhom,
Can you please tell me what are you using for generated releases? These tags look great :)

**Comment by WrathChaos** [comment]
@gorhom Still waiting for your help :)

**Comment by gorhom** [comment]
hi @WrathChaos, seems to me you did note override the `safeAreaInsets`
https://github.com/gorhom/react-native-animated-tabbar/blob/a48e3b8e6fd55e2968556814c9d10a9b25b9a2bb/example/src/screens/FlashyStyled.tsx#L84-L120

**Comment by WrathChaos** [comment]
```
 const { bottom } = useSafeArea();
  const screenPaddingBottom = React.useMemo(() => {
    // icon size + margin padding + outer space + inner space + screen bottom padding
    return 20 + bottom + 12 * 2 + 12 * 2 + 12;
  }, [bottom]);

  const tabBarOptions = React.useMemo(
    () => ({
      safeAreaInsets: {
        bottom: 0,
      },
      style: {
        position: "absolute",
        left: 0,
        right: 0,
        bottom: 0,
        borderRadius: 16,
        marginLeft: 32,
        marginRight: 32,
        marginBottom: bottom,
        backgroundColor: "#000",
        shadowColor: "#000",
        shadowOffset: {
          width: 0,
          height: 12,
        },
        shadowOpacity: 0.58,
        shadowRadius: 16.0,
        elevation: 24,
      },
    }),
    [bottom]
  );

  return (
    <Tab.Navigator
      tabBarOptions={tabBarOptions}
      tabBar={(props) => (
        <AnimatedTabBar
          preset="flashy"
          tabs={tabs}
          iconSize={20}
          itemOuterSpace={0}
          itemInnerSpace={20}
          {...props}
        />
      )}
    >
      <Tab.Screen
        name="Shop"
        component={ShopScreen}
        initialParams={{
          paddingBottom: screenPaddingBottom,
        }}
      />
      <Tab.Screen
        name="Search"
        component={SearchScreen}
        initialParams={{
          paddingBottom: screenPaddingBottom,
        }}
      />
      <Tab.Screen
        name="Upcoming"
        component={UpcomingScreen}
        initialParams={{
          paddingBottom: screenPaddingBottom,
        }}
      />
      <Tab.Screen
        name="MyLove"
        component={MyLove}
        initialParams={{
          paddingBottom: screenPaddingBottom * 100,
        }}
      />
    </Tab.Navigator>
  );
```

@gorhom Do you think what is it wrong? I could not find what I am doing it wrong.

**Comment by gorhom** [comment]
i am testing your code locally and it works fine, make sure to install the latest version `v1.5.1`
<img width="839" alt="Screenshot 2020-06-13 at 11 42 57" src="https://user-images.githubusercontent.com/4061838/84565684-0da14480-ad6b-11ea-83f5-97758166c938.png">

**Comment by WrathChaos** [comment]
@gorhom Thank you so much for helping me :) I sometimes hate React Native. It simply did not update the library :S 
Now TabBar looks lovely! Thank you so much again :)
