### ISSUE TITLE
Tapping on icons tabbar nothing happens (Android)

### ISSUE THREAD

**Issue by hadnet** [gorhom/react-native-animated-tabbar#47]
# Bug

When tapping nothing happens

## Environment info

OS: Android 10
| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/animated-tabbar         | 1.5.1   |
| react-native                    | 0.62.2   |
| react-native-reanimated         | 1.8.0   |
| react-native-gesture-handler    | 1.6.1   |
| react-native-svg                | 12.1.0   |

## Steps To Reproduce

GIF attached

On iOS all is working perfect.

![Screen-Recording-2020-06-10-at-4 54 13-AM](https://user-images.githubusercontent.com/13828833/84242953-e8e16e80-aad7-11ea-9157-4509f0d2b904.gif)

**Comment by hadnet** [comment]
Sorry, it was just an error in complementary packages installations in order to work. Closing

**Comment by simvirakaiml** [comment]
@hadnet how did you fix this problem? I am facing this as well.

**Comment by ramssuthar** [comment]
@hadnet please tell how did you fix it.

**Comment by kuldip-techholding** [comment]
I'm facing the same issue. Any solution for that???? Plz

**Comment by ugrdursun** [comment]
@hadnet Cant solve this issue too. Any solution ??
