### ISSUE TITLE
Flashy: Custom icon component error

### ISSUE THREAD

**Issue by WrathChaos** [gorhom/react-native-animated-tabbar#48]
Here I am again :)

# Bug

When I try to use a custom icon component, it simply gives me this error. 

![CleanShot 2020-06-13 at 23 53 08](https://user-images.githubusercontent.com/6813862/84578814-41af5080-add1-11ea-910c-b1fe56aaf6d4.png)

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/animated-tabbar         | 1.5.1   |
| react-native                    | 0.61.5   |
| react-native-reanimated         | 1.9.0  |
| react-native-gesture-handler    | 1.6.1   |
| react-native-svg                | 12.1.0  |

## Steps To Reproduce

You can even use react-native-vector-icons. It works below 1.5.1 but not works on 1.5.1. 

```
import Icon from "react-native-dynamic-vector-icons";

Upcoming: {
    labelStyle: {
      color: "#faeb5b",
    },
    icon: {
      component: (
        <Icon name="energy" type="SimpleLineIcons" size={20} color="#faeb5b" />
      ),
      color: "rgba(230,169,25,0.8)",
    },
  },
```

Describe what you expected to happen:

1. I would like to use custom icon component for flashy preset.

**Comment by gorhom** [comment]
Hi @WrathChaos, 

[looking at its type](https://github.com/gorhom/react-native-animated-tabbar/blob/master/docs/flashy-preset.md#flashytabconfig-1), it should be 

`React.FC<FlashyTabIconProps> | React.ComponentClass<FlashyTabIconProps>`
 
this should work 👇
```ts
icon: (props) => <Icon name="energy" type="SimpleLineIcons"  {...props} />
```

**Comment by WrathChaos** [comment]
Thank you so much! It works with this way :)
