### ISSUE TITLE
Navigation events not fired correctly 

### ISSUE THREAD

**Issue by MohamadKh75** [gorhom/react-native-animated-tabbar#54]
# Bug

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/animated-tabbar         | 1.6.0   |
| react-native                    | 0.61.5   |
| react-native-reanimated         | 1.9.0   |
| react-native-gesture-handler    | 1.6.1   |
| react-native-svg                | 12.1.0   |

## Steps To Reproduce

1. Create a simple tab bar with 2 pages
2. Use redux or [`reactn`](https://github.com/CharlesStover/reactn) to change some data in tab A
3. Try to render conditionally based on data changed from tab A 

Describe what you expected to happen:

1. I expect to see the updates in tabs!
2. If I use the default react-navigation tab bar, it's working correctly! (try to comment out the `tabBarComponent: TabBar` line in `createBottomTabNavigator()` options)

## Reproducible sample code

```
null
```

**Comment by gorhom** [comment]
hi @MohamadKh75 ,

hmm that's not navigation events, its the tab them self not re-rendering when you add/remove tabs ? right ?

**Comment by MohamadKh75** [comment]
Hey @gorhom 

Well, it's version 4 so i won't add/remove tabs dynamically! But the problem is about NOT re-rendering 👌🏻

**Comment by gorhom** [comment]
could you provide a simple reproducible code, so i could look into it quick.

thanks

**Comment by MohamadKh75** [comment]
> could you provide a simple reproducible code, so I could look into it quick.
> 
> thanks

Sure @gorhom!
Take a look at [here](https://github.com/MohamadKh75/TabBarBugDemo)!

P.S: if you comment out [this line](https://github.com/MohamadKh75/TabBarBugDemo/blob/694e71851d44ad5231d8c7bcb42e1cd55b6b7638/src/Router.js#L39), it will work just fine :thinking:

**Comment by gorhom** [comment]
hi @MohamadKh75 ,

i briefly investigate the issue, and it seems some thing went wrong with `ReactN`, not sure why, but i got your code working by replacing your B & C screens with the following:

## B Screen
```tsx
import React, { useGlobal } from 'reactn';
import { View, Text } from 'react-native';

export const B = () => {
  const [{ flag }] = useGlobal();
  return (
    <View style={{ flex: 1, justifyContent: 'center', alignItems: 'center' }}>
      <Text>Flag is {flag === true ? 'True' : 'False'}</Text>
    </View>
  );
};
```

# C Screen

```tsx
import React, { useGlobal } from 'reactn';
import { View, Button } from 'react-native';

const C = () => {
  const [global, setGlobal] = useGlobal();
  return (
    <View style={{ flex: 1, justifyContent: 'center', alignItems: 'center' }}>
      <Button
        title='Change the flag!'
        onPress={() => setGlobal(prevState => ({ flag: !prevState.flag }))}
      />
    </View>
  );
};

export { C };
```

hope it help you 👍

**Comment by MohamadKh75** [comment]
Thanks for your help and effort ❤

If the problem is with `reactn`, then why commenting [this line](https://github.com/MohamadKh75/TabBarBugDemo/blob/694e71851d44ad5231d8c7bcb42e1cd55b6b7638/src/Router.js#L39), solve the problem 🤔?

Any idea?

**Comment by MohamadKh75** [comment]
@gorhom ping :grin:

**Comment by gorhom** [comment]
hi @MohamadKh75 , sorry i didn't reply earlier, however, i still do not know what is the issue 🤷‍♂️

since its not related directly to react-navigation or this library, i am afraid i won't be spending time on it, however if you are interested to investigate it further, feel free to submit a pr to resolve the issue, if not, i will have to close this issue 

good luck

**Comment by MohamadKh75** [comment]
Okay then
Tnx ❤
