### ISSUE TITLE
keyboardHidesTabBar option doesn't work

### ISSUE THREAD

**Issue by xxczaki** [gorhom/react-native-animated-tabbar#55]
# Bug

Adding `tabBarOptions={{keyboardHidesTabBar: true}}` on either `Tab.Navigator` component from React Navigation 5.x or `AnimatedTabBar` from this library doesn't work - the tab bar still shows above keyboard.

Tested on Android v10 Emulator

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/animated-tabbar         | 1.6.0   |
| react-native                    | 0.62.2   |
| react-native-reanimated         | 1.9.0   |
| react-native-gesture-handler    | 1.6.1   |
| react-native-svg                | 12.1.0   |

## Steps To Reproduce

1. Use the example with React Navigation 5.x;
2. Try adding `tabBarOptions={{keyboardHidesTabBar: true}}` to `Tab.Navigator`

Describe what you expected to happen:

1. Adding `tabBarOptions={{keyboardHidesTabBar: true}}` should hide the tab bar when using keyboard

## Reproducible sample code

```js
<Tab.Navigator
	tabBarOptions={{
		keyboardHidesTabBar: true
	}}
	tabBar={props => (
		<AnimatedTabBar style={{backgroundColor: '#272727'}} tabs={tabs} {...props}/>
	)}
>
```

**Comment by xxczaki** [comment]
My bad - I did not clear the recent build, after doing so everything works fine!

**Comment by ugrdursun** [comment]
> My bad - I did not clear the recent build, after doing so everything works fine!

Clearing recent build you mean npm cache clean ?
