### ISSUE TITLE
JS version

### ISSUE THREAD

**Issue by sadikyalcin** [gorhom/react-native-animated-tabbar#58]
# Question

Hi, thanks for creating this. Could you provide a working JS example? I'm trying to convert but having problems left right centre!

**Comment by gorhom** [comment]
hi @sadikyalcin , thanks for suggesting this, i will add a JS example on next release 🙂

**Comment by gorhom** [comment]
i have updated the readme file to include JS example

https://github.com/gorhom/react-native-animated-tabbar#usage
