### ISSUE TITLE
i can't do with JS

### ISSUE THREAD

**Issue by PhamToan-kk** [gorhom/react-native-animated-tabbar#64]
Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.

Check the render method of `BubbleTabBarItemComponent`.

This error is located at:
    in RCTView (at BubbleTabBarItem.tsx:166)
    in RCTView (at createAnimatedComponent.js:233)
    in AnimatedComponent(Component) (at BubbleTabBarItem.tsx:165)
    in RCTView (at createAnimatedComponent.js:233)
    in AnimatedComponent(Component) (at BubbleTabBarItem.tsx:164)
    in BubbleTabBarItemComponentit
    in BubbleTabBarItemComponent (at BubbleTabBar.tsx:78)
    in RCTView (at createAnimatedComponent.js:233)
    in AnimatedComponent(Component) (at RawButton.tsx:109)
    in LongPressGestureHandler (at RawButton.tsx:105)
    in RCTView (at createAnimatedComponent.js:233)
    in AnimatedComponent(Component) (at RawButton.tsx:96)
    in TapGestureHandler (at RawButton.tsx:92)
    in RawButton (at BubbleTabBar.tsx:70)
    in RCTView (at BubbleTabBar.tsx:67)
 
it is my code by JS : 
<img width="775" alt="Screenshot 2020-07-20 at 00 45 46" src="https://user-images.githubusercontent.com/48961248/87881269-5f9c5080-ca22-11ea-88ef-de81ddeb12c5.png">

and below image i do the same Docs

**Comment by loureirorg** [comment]
Just for the sake of documentation, the error is that `component` expects a function:
```js
component: (props) => <VectorIcon MaterialCommunityIcons name="home" size={20} />
```

_PS: I believe you already know how to fix this because the ticket is closed, but I am writing the solution here to help anyone that arrives with the same problem. I had this same issue and found this page with no solution, that's why I am writing the solution._

**Comment by rossjohnsonMP** [comment]
![Screenshot 2020-07-28 at 16 28 13](https://user-images.githubusercontent.com/44770156/88686803-5df01e00-d0ef-11ea-8de4-2ece6eb3852c.png)

I'm using react navigation 4 and not typescript and i cant seem to get it to work?

**Comment by gorhom** [comment]
@rossjohnsonMP , could you create another issue for your issue, it seems different than this issue, thanks
