### ISSUE TITLE
tabBarVisible not working

### ISSUE THREAD

**Issue by Alarees** [gorhom/react-native-animated-tabbar#68]
# Bug

react navigation provide `options` props in the `Tab.Screen`, one of the  options you pass to `options` is `tabBarVisible` as everyone knows, when using Tab navigator without this lib the `tabBarVisible` works fine, but when i integrate it with this lib it stop working, the tab bar still visible even i pass the `tabBarVisible` and set it to false

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/animated-tabbar         | 2.0.0   |
| react-native                    | 0.61.5   |
| react-native-reanimated         | 1.9.0   |
| react-native-gesture-handler    | 1.6.1   |
| react-native-svg                | 12.1.0   |

**Comment by gorhom** [comment]
thanks for reporting this issue , i'll look into it 👍

**Comment by Alarees** [comment]
Hi, i update the lib to the last release (2.0.1) and it's not working

**mini code :**

```
<Tab.Screen name="Messages" options={{tabBarVisible:false}} component={Messages} />
```

**Comment by Alarees** [comment]
i don't know why, but suddenly it works.
thanks
