### ISSUE TITLE
Adding to borderRadius to tabBarOptions leave a white background. Can not add radius to the Tab Bar. 

### ISSUE THREAD

**Issue by thegitparticle** [gorhom/react-native-animated-tabbar#72]
# Bug
When I try to add some curvature to the edges of the Tab Bar (so it doesn't look like a perfect rectangle), the Tab Bar does bend the edges but the background of the Tab Bar has  a white background which ruins the whole point.

The only custom options I added to the given implementation in the README file is adding of these Tabbar options - 
`
tabBarOptions={{
        style: {
          backgroundColor: '#181818',
          borderRadius: 30,
          borderTopWidth: 2,
          borderColor: 'rgba(255, 255, 255, 0.1)',
        },
      }}
`

FYI: Removing everything else from the above tabBarOptions, except for borderRadius also produces the same issue of white background.

Here is the image of how it looks now. 
![20200829_201102 (1)](https://user-images.githubusercontent.com/12975157/91639518-b8550500-ea34-11ea-8225-fb6ac0c71a6d.jpg)

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/animated-tabbar         | 2.0.0  |
| react-native                    | 0.63.2 |
| react-native-reanimated         | 1.9.0  |
| react-native-gesture-handler    | 1.6.1  |
| react-native-svg                | ^12.1.0 |

## Steps To Reproduce

1. Add borderRadius to tabBarOptions
2. The Tab bar does have a radius now, but there is a white background in the back which ruins the whole point.
3. 

Describe what you expected to happen:

1. There should be a way to add radius to the white background in the back as well or it has to be transparent, so, more custom tab bars on top of the brilliant TabBar provided by this package
2.

## Reproducible sample code

`
<TabHere.Navigator
      initialRouteName="Clubs"
      tabBarOptions={{
        style: {
          backgroundColor: '#181818',
          borderRadius: 30,
          borderTopWidth: 2,
          borderColor: 'rgba(255, 255, 255, 0.1)',
        },
 }}
   tabBar={(props) => (
        <AnimatedTabBar
          tabs={tabs}
          preset="flashy"
          keyboardHidesTabBar={true}
          iconSize={20}
          itemContainerWidth="fill"
          {...props}
        />
)}>
`

**Comment by thegitparticle** [comment]
Solution: Just change the default theme settings of Navigation Container.

**Comment by Yasir12598** [comment]
@KeneePatel 

```
import { DefaultTheme } from '@react-navigation/native';
import colors from '../Config/colors';
export default {
    ...DefaultTheme,
    colors: {
        ...DefaultTheme.colors,
        primary: colors.primary,
        background: colors.background,   // provide same color as your component have, in this way you will remove white 
                                    color or what else color that appears after providing borderRadis.
        card: colors.white,
        text: colors.fontDark,
        
    },

}
```

to know about the Theme goto----->   https://reactnavigation.org/docs/themes/
