### ISSUE TITLE
animated-tabbar is not working with Drawer Navigator

### ISSUE THREAD

**Issue by graphtobinary** [gorhom/react-native-animated-tabbar#73]
Find below my Navigator

working Fine on IOS  but in android Tab is not working , 
but when i change createDrawerNavigator to createStackNavigator it will work like a charm 

Thanks in Advance 

// Root Navigatorts
const RootNavigator = createDrawerNavigator(
  {
    Home: {
      screen: TabNavigator,
    },
    Profile: {
      screen: Profile,
    },
  },
  {
    contentComponent: drawerContentComponents,
    drawerBackgroundColor:'#FAFAFA',
    // drawerWidth:Dimensions.get('window').width,
  }
);

const TabNavigator = createBottomTabNavigator(
	{
		Explore: Explore,
    Gallery: Gallery,
    Membership: Explore,
    Shop: Gallery,
  },
	{
    tabBarComponent: props => <AnimatedTabBar tabs={tabs}  {...props} />,
  },
  
);

**Comment by gorhom** [comment]
Hi @graphtobinary would you please update the issue and follow the reporting bug template so i could help you ? thanks
