### ISSUE TITLE
TypeError: undefined is not an object (evaluating 'navigation.state')

### ISSUE THREAD

**Issue by GustavoDev764** [gorhom/react-native-animated-tabbar#85]
# Bug
<p>type errors The Tabnavigator tabBar parameter receives a React.ReactNode or undefine component, however AnimatedTabBar and of type JSX Element</p>

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/animated-tabbar         | ^2.1.0  |
| react-native                    |  0.63.3 |
| react-native-reanimated         | ^1.13.1 |
| react-native-gesture-handler    | ^1.8.0 |
| react-native-svg           | ^12.1.0  |

    

## Steps To Reproduce

1. Usage  - React Navigation v5 (TypeScript)
2. 
3. 

Describe what you expected to happen:

1.
![codigo](https://user-images.githubusercontent.com/59968150/97372690-f636a400-1892-11eb-89bf-7d79876ad0dd.png)

![erro](https://user-images.githubusercontent.com/59968150/97372615-cdaeaa00-1892-11eb-97a3-fb96a77e4c83.png)

![Screenshot_20201027-181840](https://user-images.githubusercontent.com/59968150/97372217-dce12800-1891-11eb-8619-3ea866161007.png)

![terminal](https://user-images.githubusercontent.com/59968150/97373190-26cb0d80-1894-11eb-9a4e-70d5342ff93a.png)

2.

## Reproducible sample code
```
import React from 'react';
import {NavigationContainer} from '@react-navigation/native';
import {createBottomTabNavigator} from '@react-navigation/bottom-tabs';
import AnimatedTabBar, {
  TabsConfig,
  BubbleTabBarItemConfig,
} from '@gorhom/animated-tabbar';

import HomeIcon from '../Tab/icons/Home';
import ProfileIcon from '../Tab/icons/ProfileIcon';

import Home from '../../screens/Home';
import Profile from '../../screens/Profile';

const tabs: TabsConfig<BubbleTabBarItemConfig> = {
  Home: {
    labelStyle: {
      color: '#5B37B7',
    },
    icon: {
      component: <HomeIcon />,
      activeColor: 'rgba(91,55,183,1)',
      inactiveColor: 'rgba(0,0,0,1)',
    },
    background: {
      activeColor: 'rgba(223,215,243,1)',
      inactiveColor: 'rgba(223,215,243,0)',
    },
  },
  Profile: {
    labelStyle: {
      color: '#1194AA',
    },
    icon: {
      component: <ProfileIcon />,
      activeColor: 'rgba(17,148,170,1)',
      inactiveColor: 'rgba(0,0,0,1)',
    },
    background: {
      activeColor: 'rgba(207,235,239,1)',
      inactiveColor: 'rgba(207,235,239,0)',
    },
  },
};

const Tab = createBottomTabNavigator();

export default function App() {
  return (
    <NavigationContainer>
      <Tab.Navigator
        tabBar={(props) => {
          console.log(props);
          return <AnimatedTabBar tabs={tabs} />;
        }}>
        <Tab.Screen name="Home" component={Home} />
        <Tab.Screen name="Profile" component={Profile} />
      </Tab.Navigator>
    </NavigationContainer>
  );
}

```

**Comment by gorhom** [comment]
you need to pass `tabBar` props to `AnimatedTabBar`

```tax
export default function App() {
  return (
    <NavigationContainer>
      <Tab.Navigator
        tabBar={(props) => {
          console.log(props);
          return <AnimatedTabBar tabs={tabs} {...props} />;
        }}>
        <Tab.Screen name="Home" component={Home} />
        <Tab.Screen name="Profile" component={Profile} />
      </Tab.Navigator>
    </NavigationContainer>
  );
}
```
