### ISSUE TITLE
react-native-svg could not be found

### ISSUE THREAD

**Issue by Angelk90** [gorhom/react-native-animated-tabbar#88]
# Bug

<img width="398" alt="Schermata 2020-11-18 alle 15 22 07" src="https://user-images.githubusercontent.com/20476002/99545267-7db89400-29b5-11eb-9202-863efab48c65.png">

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/animated-tabbar         | ^2.1.0   |
| react-native                    | 0.63.3   |
| react-native-reanimated         | ^1.13.0  |
| react-native-gesture-handler    | ^1.8.0   |
| react-native-svg                | ^12.1.0   |

## Steps To Reproduce

1. I have installed the module.
2. pod install 
3. npx react-native link
4. I started app.

@gorhom : Shouldn't it be a dev dependencies?

**Comment by gorhom** [comment]
hi @Angelk90 , in [Installation](https://github.com/gorhom/react-native-animated-tabbar#installation), i mentioned

>Also, you need to install react-native-reanimated, react-native-gesture-handler & react-native-svg, and follow their installation instructions.

it seems you did not install `react-native-svg` correctly , please try to install it again and install `pod` again
