### ISSUE TITLE
Change the label tab bar

### ISSUE THREAD

**Issue by Angelk90** [gorhom/react-native-animated-tabbar#90]
# Feature Request
Being able to change the label of the tab bars.

![](https://github.com/gorhom/react-native-animated-tabbar/blob/master/docs/previews/bubble.gif?raw=true)

## Why it is needed

Hi @gorhom , Taking the bubble type as an example but it applies to everyone, I would need the way to change the label of the Screen Tab, the reason is that I allow the user to select the language based on the selected language I would like to show a different label (it depends language) next to the icon.

Example:
Search (en)
Cerca (it)
Rechercher (fr)

**Comment by hugoh59** [comment]
Have you tried, adding a label prop to the tab element ? It worked for me. Coupled with a translation library it should work.

**Comment by Angelk90** [comment]
@hugoh59 : Do you use i18n or something similar?

**Comment by hugoh59** [comment]
had issues with i18m, I'm using react-native-localization.

**Comment by hugoh59** [comment]
Unrelated, but did you manage to change the icon color when the tab changes ? @Angelk90 for me I get a wierd object returning from the props, not the active or color prop I'm waiting for.

**Comment by gorhom** [comment]
duplicated https://github.com/gorhom/react-native-animated-tabbar/issues/44
