### ISSUE TITLE
TypeError: (0, _reactNativeRedash.useValue) is not a function. (In '(0, _reactNativeRedash.useValue)(0)', '(0, _reactNativeRedash.useValue)' is undefined)

### ISSUE THREAD

**Issue by AkhilSobhana** [gorhom/react-native-animated-tabbar#96]
TypeError: (0, _reactNativeRedash.useValue) is not a function. (In '(0, _reactNativeRedash.useValue)(0)', '(0, _reactNativeRedash.useValue)' is undefined)**

Please help to solve this

**Comment by Raghavendrareddy5121** [comment]
> TypeError: (0, _reactNativeRedash.useValue) is not a function. (In '(0, _reactNativeRedash.useValue)(0)', '(0, _reactNativeRedash.useValue)' is undefined)**
> 
> Please help to solve this

Im also getting same error

**Comment by mzohrab** [comment]
Downgrading to 2.1.1 version works ok.

**Comment by chrismathews2007** [comment]
**TypeError: (0, _reactNativeRedash.useValues) is not a function. (In '(0, _reactNativeRedash.useValues)(0)', '(0, _reactNativeRedash.useValues)' is undefined)**

using versions
"react-native-reanimated": "~2.8.0",
"react-native-redash": "^18.0.0",

Please help me to overcome this.
